MyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('autoshop/', include('autoshop.urls')),
    path('travel/', include('travel.urls')),
    path('vehicle/', include('vehicle.urls')),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    path('contact/', include('contact.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('a/', views.after_login, name='afterlogin')
]

vehicle/urls.py
from django.urls import path
from . import views

# urlpatterns = [
#     path('', views.home)
# ]

from django.urls import path
from . import views

app_name = 'vehicle'
urlpatterns = [
    path('add/', views.add_vehicle, name='add_vehicle'),
    path('bike_view/', views.bike_show, name='bike_view'),
    path('car_view/', views.car_show, name='car_view'),
    path('booking/<int:id>', views.vehicle_book, name='vehicle_book'),
    path('vehicle_details/<int:id>/', views.vehicle_details, name='vehicle_details'),
]

vehicle/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
from accounts.models import MyUser


class VehicleType(models.Model):
    type = models.CharField(max_length=100)
    type_desc = models.CharField(max_length=100)

    def __str__(self):
        return self.type


class Vehicle(models.Model):
    owner = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    number_plate = models.CharField(max_length=20)
    vehicle = models.ImageField()
    km_driven = models.PositiveSmallIntegerField()
    seat = models.PositiveSmallIntegerField()
    price_per_day = models.CharField(max_length=100)
    wheeler = models.CharField(max_length=100)
    transmission = models.CharField(max_length=100)
    type = models.ForeignKey(VehicleType, on_delete=models.CASCADE)
    details = models.CharField(max_length=100)
    is_available = models.CharField(max_length=100, default=True)
    is_booked = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class VehicleBooking(models.Model):
    owner = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='owner')
    buyer = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='buyer')
    order_date = models.DateField()
    order_expire_date = models.DateField()
    total_price = models.PositiveIntegerField()

vehicle/forms.py
from django import forms
from .models import Vehicle


class VehicleForms(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = [
            'name',
            'km_driven',
            'seat',
            'price_per_day',
            'wheeler',
            'transmission',
            'type',
            'details',
            'number_plate',
            'vehicle',
        ]

vehicle/views.py
from django.shortcuts import render, redirect
from vehicle.models import VehicleBooking, Vehicle,VehicleType
from datetime import datetime
from accounts.models import MyUser
from django.db.models import Q
from django.contrib.auth.decorators import login_required


# Create your views here.


def home(request):
    return render(request, 'vehicle/vechile.html', )


from django.shortcuts import render
from .forms import VehicleForms
from .models import Vehicle


# Create your views here.

def add_vehicle(request):
    forms=VehicleForms()
    if request.method == 'POST':

        forms = VehicleForms(request.POST, request.FILES)
        if forms.is_valid():

            vehicle = Vehicle(
                owner=request.user,
                name=request.POST.get('name'),
                km_driven=request.POST.get('km_driven'),
                seat=request.POST.get('seat'),
                price_per_day=request.POST.get('price_per_day'),
                wheeler=request.POST.get('wheeler'),
                transmission=request.POST.get('transmission'),
                type=VehicleType.objects.get(id=request.POST.get('type')),
                details=request.POST.get('details'),
                number_plate=request.POST.get('number_plate'),
                vehicle=request.FILES['vehicle'],
            )

            vehicle.save()
        else:
            print(forms.errors)
            types = VehicleType.objects.all()
            context = {"errors": forms.errors, "types": types}
            return render(request, 'vehicle/addVehicle.html', context)
    types = VehicleType.objects.all()
    context = {"types": types,"forms":forms}
    return redirect('profiles:view')


def bike_show(request):
    vehicles = Vehicle.objects.filter(
        Q(type__type='bike') & Q(is_available=True)
    )
    context = {"vehicles": vehicles}
    return render(request, 'vehicle/vechile.html', context)


def car_show(request):
    vehicles = Vehicle.objects.filter(Q(type__type='car') & Q(is_available=True))
    context = {"vehicles": vehicles}
    return render(request, 'vehicle/vechile.html', context)


@login_required
def vehicle_book(request, id):
    if request.method == 'POST':
        order_date = request.POST.get('order_date')
        order_expire_date = request.POST.get('order_expire_date')
        vehicle = Vehicle.objects.get(id=id)

        booking = VehicleBooking(
            owner=vehicle.owner,
            buyer=request.user,
            order_date=request.POST.get('order_date'),
            order_expire_date=request.POST.get('order_expire_date'),
            total_price=vehicle.price_per_day

        )
        booking.save()
        Vehicle.objects.filter(id=id).update(is_booked=True, is_available=False)
        return redirect('/')


def vehicle_details(request, id):
    vehicle = Vehicle.objects.get(id=id)
    context = {"vehicle": vehicle, "id": id}
    return render(request, 'vehicle/vehicle_details.html', context)

vehicle/templates/vehicle/addVehicle.html
{% load static %}

{{ errors }}
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    name:<input type="text" name="name"><br>
    number plate:<input type="text" name="number_plate"><br>
    Vehicle Photo:<input type="file" name="vehicle" accept="image/*"><br>
    km_driven:<input type="number" name="km_driven"><br>
    price_per_day:<input type="number" name="price_per_day"><br>
    wheeler:<input type="number" name="wheeler"><br>
    seat:<input type="number" name="seat"><br>
    transmission:<input type="text" name="transmission"><br>
    type:
    <select name="type">
            <option value="">Select Vehicle Type</option>

        {% for type in types %}
        <option value="{{ type.id }}">{{ type }}</option>
        {% endfor %}
    </select><br>
    details:<input type="text" name="details"><br>
    <input type="submit" value="submit"><br>
</form>
{#<form method="post">#}
{#        {% csrf_token %}#}
{##}
{#    <input type="hidden" name="csrfmiddlewaretoken"#}
{#           value="35I27Mu6jpqKX1U7ZYAfbVLoVKrG2sQBZQRZQZdGPpFc7HSsdqjmgdJNbAgVEEVE">#}
{#    <p><label for="id_name">Name:</label> <input type="text" name="name" maxlength="100" required="" id="id_name"></p>#}
{#    <p><label for="id_km_driven">Km driven:</label> <input type="number" name="km_driven" min="0" required=""#}
{#                                                           id="id_km_driven"></p>#}
{#    <p><label for="id_seat">Seat:</label> <input type="number" name="seat" min="0" required="" id="id_seat"></p>#}
{#    <p><label for="id_price_per_day">Price per day:</label> <input type="text" name="price_per_day" maxlength="100"#}
{#                                                                   required="" id="id_price_per_day"></p>#}
{#    <p><label for="id_wheeler">Wheeler:</label> <input type="text" name="wheeler" maxlength="100" required=""#}
{#                                                       id="id_wheeler"></p>#}
{#    <p><label for="id_transmission">Transmission:</label> <input type="text" name="transmission" maxlength="100"#}
{#                                                                 required="" id="id_transmission"></p>#}
{#    <p><label for="id_type">Type:</label> <select name="type" required="" id="id_type">#}
{#        <option value="" selected="">---------</option>#}
{##}
{#        <option value="1">car</option>#}
{##}
{#        <option value="2">bike</option>#}
{##}
{#    </select></p>#}
{#    <p><label for="id_details">Details:</label> <input type="text" name="details" maxlength="100" required=""#}
{#                                                       id="id_details"></p>#}
{#    <p><label for="id_number_plate">Number plate:</label> <input type="text" name="number_plate" maxlength="20"#}
{#                                                                 required="" id="id_number_plate"></p>#}
{#    <p><label for="id_vehicle">Vehicle:</label> <input type="file" name="vehicle" accept="image/*" required=""#}
{#                                                       id="id_vehicle"></p>#}
{#</form>#}
{#<form method="post">#}
{#    {% csrf_token %}#}
{#    {{ forms.as_p }}#}
{#</form>#}

vehicle/templates/vehicle/vechile.html
{% extends "home/base.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'vehicle/css/vehicle_custom.css' %}">{% endblock %}

{% block script %}
{% endblock %}

{% block title %}- Login {% endblock %}

{% block content %}


    <section class="section" id="trainers">
        <div class="container">
            <br>
            <br>
            <div class="row">
                {% for vehicle in vehicles %}
                    <div class="col-lg-4 col-md-4">
                        <div class="trainer-item">
                            <div class="image-thumb">
                                <img src="{{ vehicle.vehicle.url }}" alt="" width="300px" height="170px">
                            </div>
                            <div class="down-content">
                                <span>Price Per Day <sup>Rs.</sup>{{ vehicle.price_per_day }}</span>
                                <h4>{{ vehicle.name }}</h4>
                                <p>
                                    <i class="fa fa-user" title="passegengers"></i> {{ vehicle.seat }} &nbsp;&nbsp;&nbsp;
                                    <i class="fa fa-sign-out" title="doors"></i> {{ vehicle.wheeler }} &nbsp;&nbsp;&nbsp;
                                    <i class="fa fa-cog" title="transmission"></i> {{ vehicle.transmission }}
                                </p>
                                <ul class="social-icons">
                                    <li><a href="{% url 'vehicle:vehicle_details'  vehicle.id %}">+ View Detials</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </section>

{% endblock %}

vehicle/templates/vehicle/vehicle_details.html
{% extends "home/base.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'vehicle/css/overview_custom.css' %}">{% endblock %}
{% block script %}
{% endblock %}

{% block title %}- OverView {% endblock %}

{% block content %}

    <div class="wrapper">
        <div class="container">

            <section>
                <div class="jumbotron">
                    <div class="container">
                        <h2> {{ vehicle.name }} </h2>

                        <div class="split">
                            <div>

                                <img src="{{ vehicle.vehicle.url }}" alt="" height="370" width="500">

                            </div>
                            <div>
                                <ul>Name: {{ vehicle.name }}</ul>
                                <ul>number plate:{{ vehicle.number_plate }}</ul>
                                <ul>km driven: {{ vehicle.km_driven }}</ul>
                                <ul>vehicle seat: {{ vehicle.seat }}</ul>
                                <ul>price per day: {{ vehicle.price_per_day }}</ul>
                                <ul> wheeler: {{ vehicle.wheeler }}</ul>
                                <ul>transmission {{ vehicle.transmission }}</ul>
                                <ul>details: {{ vehicle.details }}</ul>
                                <form method="post" action="{% url 'vehicle:vehicle_book' id %}">
                                    {% csrf_token %}


                                    <ul>from date:<input type="date" name="order_date" required></ul>
                                    <ul>end date:<input type="date" name="order_expire_date" required></ul>
                                    <ul><input type="submit" class="btn btn-primary" value="Book Now"></ul>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

        </div>
    </div>


{% endblock %}