MyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('autoshop/', include('autoshop.urls')),
    path('travel/', include('travel.urls')),
    path('vehicle/', include('vehicle.urls')),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    path('contact/', include('contact.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login,name='login'),
    path('register/', views.register,name='register'),
    path('home/', views.homepage,name='homepage'),
    path('logout/',views.logout,name='logout')
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('a/', views.after_login, name='afterlogin')
]

profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"

urlpatterns = [
    path('create/', views.create, name='create'),
    path('view/',views.view, name='view')
]

vehicle/urls.py
from django.urls import path
from . import views

# urlpatterns = [
#     path('', views.home)
# ]

from django.urls import path
from . import views

app_name = 'vehicle'
urlpatterns = [
    path('add/', views.add_vehicle, name='add_vehicle'),
    path('bike_view/', views.bike_show, name='bike_view'),
    path('car_view/', views.car_show, name='car_view'),
    path('booking/<int:id>', views.vehicle_book, name='vehicle_book'),
    path('vehicle_details/<int:id>/', views.vehicle_details, name='vehicle_details'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from vehicle.models import Vehicle


# Create your views here.

def search(request):
    vehicle = Vehicle.objects.filter(name=request.GET.get('search'))
    print(vehicle)
    context = {"vehicle": vehicle}
    return render(request, 'home/search.html', context)


def home(request):
    return render(request, 'home/index.html')


def after_login(request):
    return render(request, 'home/afterlogin.html')

home/templates/home/afterlogin.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/_bootswatch.scss' %}">
    <link rel="stylesheet" href="{% static 'home/css/_variables.scss' %}">

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>


    <link rel="stylesheet" href="{% static 'home/css/nav2.css' %} ">

    {% block head %}{% endblock %}

    <title>Rental System {% block title %}{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}" style="color: orange">Rental System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse w-100 order-3 dual-collapse2" id="navbarColor02">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link mx-3" href="{% url 'home' %}" ><i class="fa fa-home"></i>&nbsp;Home
          <span class="sr-only">(current)</span>
        </a>
      </li>

         <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle mx-3" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-compact-disc"> </i>&nbsp;Vehicle</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#"><i class="fa fa-motorcycle"></i>&nbsp;Bike</a>
            <a class="dropdown-item" href="#"><i class='fas fa-car-side'></i>&nbsp;Car</a>
        </div>
      </li>


      <li class="nav-item mx-3">
        <a class="nav-link" href="{% url 'travel' %}"><i class="fas fa-atlas"></i>&nbsp;Travel</a>
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link" href="{% url 'autoshop' %}"><i class="fas fa-tools"></i>&nbsp;Auto-Shop</a>
      </li>
      <li class="nav-item mx-3">
          <a class="nav-link" href="{% url 'contact' %}"><i class="fa fa-envelope" ></i>&nbsp;Contact Us</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i>&nbsp;Me </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'accounts:register' %}"><i class="fa fa-user-circle"></i>&nbsp;View Profile</a>
          <a class="dropdown-item" href="{% url 'accounts:login' %}"><i class="fas fa-sign-out-alt"></i>&nbsp;Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

    {% block content %}


    {% endblock %}


<script src="{% static 'home/js/jquery.min.js' %}">   </script>
    <script src="{% static 'home/js/bootstrap.min.js' %}">   </script>
<script src="{% static 'home/js/popper.min.js' %}">   </script>

<script src="{% static 'home/js/custom.js' %}"></script>
{% block script %}{% endblock %}

</body>
</html>














home/templates/home/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/_bootswatch.scss' %}">
    <link rel="stylesheet" href="{% static 'home/css/_variables.scss' %}">

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>


    <link rel="stylesheet" href="{% static 'home/css/nav.css' %} ">

    {% block head %}{% endblock %}

    <title>Rental System {% block title %}{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}" style="color: orange">Rental System</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02"
            aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse w-100 order-3 dual-collapse2" id="navbarColor02">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <form method="get" action="{% url 'search' %}">
                    <input type="text" name="search">
                    <input type="submit" value="Search">
                </form>
            </li>
            <li class="nav-item active">
                <a class="nav-link mx-3" href="{% url 'home' %}"><i class="fa fa-home"></i>&nbsp;Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>


            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle mx-3" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="true" aria-expanded="false"><i class="fas fa-compact-disc"> </i>&nbsp;Vehicle</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'vehicle:bike_view' %}"><i class="fa fa-motorcycle"></i>&nbsp;Bike</a>
                    <a class="dropdown-item" href="{% url 'vehicle:car_view' %}"><i class='fas fa-car-side'></i>&nbsp;Car</a>
                </div>
            </li>


            <li class="nav-item mx-3">
                <a class="nav-link" href="{% url 'travel' %}"><i class="fas fa-atlas"></i>&nbsp;Travel</a>
            </li>
            <li class="nav-item mx-3">
                <a class="nav-link" href="{% url 'autoshop' %}"><i class="fas fa-tools"></i>&nbsp;Auto-Shop</a>
            </li>
            <li class="nav-item mx-3">
                <a class="nav-link" href="{% url 'contact' %}"><i class="fa fa-envelope"></i>&nbsp;Contact Us</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true"
                       aria-expanded="false"><i class="fas fa-user"></i>&nbsp;Me </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'profiles:view' %}"><i class="fa fa-user-circle"></i>&nbsp;View
                            Profile</a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i>&nbsp;Logout</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true"
                       aria-expanded="false"><i class="fas fa-user"></i>&nbsp;Sign Up</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'accounts:register' %}"><i class="fa fa-user-plus"></i>&nbsp;Register</a>
                        <a class="dropdown-item" href="{% url 'accounts:login' %}"><i class="fas fa-sign-in-alt"></i>&nbsp;Login</a>
                    </div>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

{% block content %}


{% endblock %}


<script src="{% static 'home/js/jquery.min.js' %}"></script>
<script src="{% static 'home/js/bootstrap.min.js' %}"></script>
<script src="{% static 'home/js/popper.min.js' %}"></script>

<script src="{% static 'home/js/custom.js' %}"></script>
{% block script %}{% endblock %}

</body>
</html>














home/templates/home/index.html
{% extends "home/base.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'home/css/image.css' %}">{% endblock %}
{% block script %}
{% endblock %}
{% block title %}- Home {% endblock %}

{% block content %}


    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">

            <div class="carousel-item active">
                <div class="carousel-caption">
                    <h2> Lets Drive</h2>
                    <button type="button" class="btn btn-danger">Book Now</button>
                </div>
                <img class="d-block w-100" src="{% static 'home/images/image2.jpg' %}" style="width: 100%"
                     alt="first slide">

            </div>
            <div class="carousel-item">
                <div class="carousel-caption">
                    <h2 style="color: Black"> Lets Ride</h2>
                    <button type="button" class="btn btn-danger">Book Now</button>
                </div>
                <img class="d-block w-100" src="{% static 'home/images/image3.jpg' %}" alt="second slide">

            </div>
            <div class="carousel-item ">
                <img class="d-block w-100" src="{% static 'home/images/image1.jpeg' %}" style="width: 100%"
                     alt="Third slide">
                <div class="carousel-caption">

                </div>
            </div>

        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div>
        {#name = models.CharField(max_length=100)#}
        {#    number_plate = models.CharField(max_length=20)#}
        {#    vehicle = models.ImageField()#}
        {#    km_driven = models.PositiveSmallIntegerField()#}
        {#    seat = models.PositiveSmallIntegerField()#}
        {#    price_per_day = models.CharField(max_length=100)#}
        {#    wheeler = models.CharField(max_length=100)#}
        {#    transmission = models.CharField(max_length=100)#}
        {#    type = models.CharField(max_length=100)#}
        {#    details = models.CharField(max_length=100)#}
        {#    is_available = models.CharField(max_length=100, default=True)#}
        {% for vechile in vehicles %}
            {{ vechile.name }}<br>
            {{ vechile.km_driven }}

        {% endfor %}
    </div>

{% endblock %}

home/templates/home/search.html
{% extends 'home/base.html' %}

{% block content %}
    {% for v in vehicle %}
        vehicle name: {{ v.name }}<br>
        <img src="{{ v.vehicle.url }}" width="400" height="200"><br>
        ************************<br><br><br>
    {% endfor %}
{% endblock %}